'use client';
import { Box, Button, HStack, Input, Select, Stack, Table, Tbody, Td, Text, Th, Thead, Tr, useDisclosure, Drawer, DrawerOverlay, DrawerContent, DrawerCloseButton, DrawerHeader, DrawerBody, FormControl, FormLabel, Textarea } from '@chakra-ui/react';
import { useMemo, useState } from 'react';
import { leads as baseLeads } from '@/data/leads';
import { Lead } from '@/types/lead';
import LeadStatusBadge from './LeadStatusBadge';

export default function LeadsTable() {
  const [search, setSearch] = useState('');
  const [status, setStatus] = useState('');
  const [selected, setSelected] = useState<Lead | null>(null);
  const { isOpen, onOpen, onClose } = useDisclosure();
  const filtered = useMemo(() => baseLeads.filter((lead) => (!search || `${lead.name} ${lead.propertyTitle}`.toLowerCase().includes(search.toLowerCase())) && (!status || lead.status === status)), [search, status]);
  const open = (lead: Lead) => { setSelected(lead); onOpen(); };
  return <Box><Stack direction={{ base: 'column', md: 'row' }} mb={5}><Input bg="white" placeholder="Search leads" value={search} onChange={(e) => setSearch(e.target.value)} /><Select bg="white" placeholder="All statuses" value={status} onChange={(e) => setStatus(e.target.value)}><option>New</option><option>Contacted</option><option>Viewing Scheduled</option><option>Negotiating</option><option>Closed</option><option>Lost</option></Select></Stack><Box display={{ base: 'none', md: 'block' }} bg="white" borderRadius="24px" overflow="hidden" border="1px solid" borderColor="brand.softGrey"><Table><Thead><Tr><Th>Lead name</Th><Th>Property</Th><Th>Contact</Th><Th>Status</Th><Th>Source</Th><Th>Date</Th><Th>Action</Th></Tr></Thead><Tbody>{filtered.map((lead) => <Tr key={lead.id}><Td fontWeight="800">{lead.name}</Td><Td>{lead.propertyTitle}</Td><Td>{lead.email}<br />{lead.phone}</Td><Td><LeadStatusBadge status={lead.status} /></Td><Td>{lead.source}</Td><Td>{lead.date}</Td><Td><Button size="sm" onClick={() => open(lead)}>View</Button></Td></Tr>)}</Tbody></Table></Box><Stack display={{ base: 'flex', md: 'none' }}>{filtered.map((lead) => <Box key={lead.id} bg="white" border="1px solid" borderColor="brand.softGrey" borderRadius="20px" p={5}><HStack justify="space-between"><Text fontWeight="900">{lead.name}</Text><LeadStatusBadge status={lead.status} /></HStack><Text color="brand.textMuted">{lead.propertyTitle}</Text><Text>{lead.email}</Text><Button mt={3} size="sm" onClick={() => open(lead)}>View details</Button></Box>)}</Stack><Drawer isOpen={isOpen} onClose={onClose} placement="right" size="md"><DrawerOverlay /><DrawerContent><DrawerCloseButton /><DrawerHeader>Lead details</DrawerHeader><DrawerBody>{selected && <Stack spacing={4}><Text fontWeight="900" fontSize="xl">{selected.name}</Text><Text>{selected.email} · {selected.phone}</Text><LeadStatusBadge status={selected.status} /><Text>{selected.message}</Text><FormControl><FormLabel>Status</FormLabel><Select defaultValue={selected.status}><option>New</option><option>Contacted</option><option>Viewing Scheduled</option><option>Negotiating</option><option>Closed</option><option>Lost</option></Select></FormControl><FormControl><FormLabel>Notes</FormLabel><Textarea placeholder="Add internal notes..." /></FormControl><FormControl><FormLabel>Follow-up reminder</FormLabel><Input type="date" /></FormControl><Button variant="primary">Save lead update</Button></Stack>}</DrawerBody></DrawerContent></Drawer></Box>;
}
